version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: nest-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: loteria-redis
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
volumes:
  postgres_data:
